# Activity in detail ----

#' Generate Activity in Detail Table
#' @param data List. Contents of the JSON generated by the inputs app.
#' @param sites Character. Location codes selected by the user from the outputs
#'     app interface.
#' @param tretspefs Data.frame. Treatment specialties lookup of codes to
#'     descriptions. Derived from internal JSON lookup.
#' @param activity_type Character. The activity type (e.g. 'ip' for inpatients).
#' @param pod Character. The point of delivery (e.g.
#'     'ip_non-elective_admission').
#' @param measure Character. A selected measure (e.g. 'beddays').
#' @param agg_col Character. Name of column to aggregate by (i.e. age,
#'     'age_group', or treatment specialty, 'tretspef').
#' @noRd
generate_activity_in_detail_table <- function(
    data,
    sites,
    tretspefs,
    activity_type,
    pod,
    measure,
    agg_col) {
  aggregated_data <- data |>
    get_aggregation(pod, measure, agg_col, sites)
  
  # if a site is selected then there are no rows for A&E
  if (nrow(aggregated_data) == 0) stop("No data")
  
  aggregated_data <- aggregated_data |>
    dplyr::transmute(
      .data$sex,
      agg = .data[[agg_col]],
      .data$baseline,
      final = .data$principal,
      change = .data$final - .data$baseline,
      change_pcnt = .data$change / .data$baseline
    )
  
  # if (agg_col == "tretspef") {
  #   aggregated_data <- aggregated_data |>
  #     dplyr::left_join(
  #       tretspefs,
  #       by = dplyr::join_by("agg" == "Code")
  #     ) |>
  #     dplyr::mutate(
  #       dplyr::across(
  #         "Description",
  #         \(x) dplyr::if_else(is.na(x), .data$agg, .data$Description)
  #       ),
  #     ) |>
  #     dplyr::select("sex", "Description", dplyr::everything(), -"agg") |>
  #     dplyr::rename("agg" = "Description")
  # }
  
  end_year <- data[["params"]][["end_year"]]
  end_fyear <- paste0(
    end_year, "/",
    as.numeric(stringr::str_extract(end_year, "\\d{2}$")) + 1
  )
  
  aggregated_data |>
    mod_principal_detailed_table(
      aggregation = agg_col,
      final_year = end_fyear
    ) |>
    gt::tab_options(table.align = "left")
}